#!/usr/bin/env python3
"""Synchronize .codex skill compatibility stubs from the routing registry."""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

if str(Path(__file__).resolve().parents[1]) not in sys.path:
    sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from scripts.orchestration_metadata import (  # noqa: E402
    CODEX_SKILLS_DIR,
    REGISTRY_PATH,
    ROUTER_MATRIX_PATH,
    _normalize_metadata_text,
    load_registry,
    load_router_matrix,
    validate_registry,
    validate_router_matrix_consistency,
    validate_router_reachability,
)


REPO_ROOT = Path(__file__).resolve().parents[1]


def expected_stub_text(skill_name: str, canonical_path: str) -> str:
    return (
        "---\n"
        f"name: {skill_name}\n"
        f"description: Codex compatibility stub for the {skill_name} plugin skill.\n"
        "generated_from: scripts/sync_codex_stubs.py\n"
        "---\n\n"
        "This file is auto-generated for OpenAI Codex skill discovery.\n"
        "Do not edit this file by hand.\n\n"
        "Canonical skill source:\n"
        f"`{canonical_path}`\n\n"
        "When this skill is selected, follow the canonical source file above.\n"
    )


def sync_stubs(*, check_mode: bool) -> int:
    registry = load_registry(REGISTRY_PATH)
    skills, errors = validate_registry(registry)
    errors.extend(validate_router_matrix_consistency(skills))

    if not errors:
        router_matrix = load_router_matrix(ROUTER_MATRIX_PATH)
        errors.extend(validate_router_reachability(skills, router_matrix))

    updated = 0
    expected_skill_names = {entry["skill_name"] for entry in skills}

    for entry in sorted(skills, key=lambda item: item["skill_name"]):
        skill_name = entry["skill_name"]
        canonical_rel = entry["canonical_path"]
        canonical_path = REPO_ROOT / canonical_rel

        if not canonical_path.exists():
            errors.append(
                f"Registry canonical_path for `{skill_name}` does not exist: {canonical_rel}"
            )
            continue

        if check_mode:
            openai_meta = canonical_path.parent / "agents" / "openai.yaml"
            if not openai_meta.exists():
                errors.append(
                    f"Missing Codex UI metadata for `{skill_name}`: "
                    f"{openai_meta.relative_to(REPO_ROOT).as_posix()}"
                )
            elif entry["trigger_mode"] == "user_triggered_only":
                metadata_text = _normalize_metadata_text(openai_meta.read_text(encoding="utf-8"))
                if "user-triggered only" not in metadata_text:
                    errors.append(
                        f"Missing user-triggered-only marker for `{skill_name}` in "
                        f"{openai_meta.relative_to(REPO_ROOT).as_posix()}"
                    )

        stub_dir = CODEX_SKILLS_DIR / skill_name
        stub_path = stub_dir / "SKILL.md"
        expected_text = expected_stub_text(skill_name, canonical_rel)

        if check_mode:
            if not stub_path.exists():
                errors.append(
                    f"Missing generated stub for `{skill_name}`: "
                    f"{stub_path.relative_to(REPO_ROOT).as_posix()}"
                )
                continue
            actual = stub_path.read_text(encoding="utf-8")
            if actual != expected_text:
                errors.append(
                    f"Stub drift detected for `{skill_name}`: "
                    f"{stub_path.relative_to(REPO_ROOT).as_posix()}"
                )
            continue

        stub_dir.mkdir(parents=True, exist_ok=True)
        if not stub_path.exists() or stub_path.read_text(encoding="utf-8") != expected_text:
            stub_path.write_text(expected_text, encoding="utf-8")
            updated += 1

    if check_mode and CODEX_SKILLS_DIR.exists():
        actual_skill_names = {
            path.name for path in CODEX_SKILLS_DIR.iterdir() if path.is_dir() and (path / "SKILL.md").exists()
        }
        extra_stubs = sorted(actual_skill_names - expected_skill_names)
        if extra_stubs:
            errors.append(
                "Found stubs not declared in registry: " + ", ".join(f"`{name}`" for name in extra_stubs)
            )

    if errors:
        print("sync_codex_stubs: validation failed", file=sys.stderr)
        for error in errors:
            print(f" - {error}", file=sys.stderr)
        return 1

    if check_mode:
        print(f"sync_codex_stubs: check passed for {len(skills)} skills")
    else:
        print(f"sync_codex_stubs: synchronized {len(skills)} skills ({updated} updated)")
    return 0


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Generate or check .codex compatibility stubs from registry metadata."
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Validate stub drift and required metadata instead of writing files.",
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    return sync_stubs(check_mode=args.check)


if __name__ == "__main__":
    raise SystemExit(main())
